"""delegations

Revision ID: da6988483193
Revises: 229565016a18
Create Date: 2026-09-28 12:49:00.024769

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da6988483193"
down_revision: str | Sequence[str] | None = "229565016a18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delegations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=False),
        sa.Column("name_fr", sa.String(length=120), nullable=False),
        sa.Column("name_ar", sa.String(length=120), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["delivery_cities.id"],
            name=op.f("fk_delegations_city_id_delivery_cities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delegations")),
        sa.UniqueConstraint("city_id", "name_fr", name="uq_delegation_name"),
    )
    op.create_index(op.f("ix_delegations_city_id"), "delegations", ["city_id"], unique=False)
    op.add_column("orders", sa.Column("delegation_id", sa.Integer(), nullable=True))
    op.add_column(
        "orders", sa.Column("delegation", sa.String(length=120), server_default="", nullable=False)
    )
    op.create_index(op.f("ix_orders_delegation_id"), "orders", ["delegation_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_orders_delegation_id_delegations"),
        "orders",
        "delegations",
        ["delegation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_orders_delegation_id_delegations"), "orders", type_="foreignkey")
    op.drop_index(op.f("ix_orders_delegation_id"), table_name="orders")
    op.drop_column("orders", "delegation")
    op.drop_column("orders", "delegation_id")
    op.drop_index(op.f("ix_delegations_city_id"), table_name="delegations")
    op.drop_table("delegations")
    # ### end Alembic commands ###
