"""arabic storefront copy

Revision ID: 5db01629a352
Revises: 957a2d6d7ee6
Create Date: 2026-09-28 11:15:52.835331

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5db01629a352"
down_revision: str | Sequence[str] | None = "957a2d6d7ee6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("name_ar", sa.String(length=120), nullable=True))
    op.add_column("delivery_cities", sa.Column("name_ar", sa.String(length=120), nullable=True))
    op.add_column("order_items", sa.Column("product_name_ar", sa.String(length=160), nullable=True))
    op.add_column("products", sa.Column("name_ar", sa.String(length=160), nullable=True))
    op.add_column(
        "products", sa.Column("description_ar", sa.Text(), server_default="", nullable=False)
    )
    op.add_column(
        "products", sa.Column("ingredients_ar", sa.Text(), server_default="", nullable=False)
    )
    op.add_column("products", sa.Column("storage_ar", sa.Text(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "storage_ar")
    op.drop_column("products", "ingredients_ar")
    op.drop_column("products", "description_ar")
    op.drop_column("products", "name_ar")
    op.drop_column("order_items", "product_name_ar")
    op.drop_column("delivery_cities", "name_ar")
    op.drop_column("categories", "name_ar")
    # ### end Alembic commands ###
