"""tnd money and delivery cities

Revision ID: 9111a79197ee
Revises: 25a206a9eecb
Create Date: 2026-09-27 13:17:49.979328

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9111a79197ee"
down_revision: str | Sequence[str] | None = "25a206a9eecb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=False),
        sa.Column("name_fr", sa.String(length=120), nullable=False),
        sa.Column("fee", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("fee >= 0", name=op.f("ck_delivery_cities_fee_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_cities")),
        sa.UniqueConstraint("name_fr", name=op.f("uq_delivery_cities_name_fr")),
    )
    op.alter_column(
        "order_items",
        "unit_price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=12, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "order_items",
        "line_total",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=12, scale=3),
        existing_nullable=False,
    )
    op.add_column("orders", sa.Column("delivery_city_id", sa.Integer(), nullable=True))
    op.alter_column(
        "orders",
        "subtotal",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=12, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "delivery_fee",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=12, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "total",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=12, scale=3),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_orders_delivery_city_id"), "orders", ["delivery_city_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_orders_delivery_city_id_delivery_cities"),
        "orders",
        "delivery_cities",
        ["delivery_city_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "products",
        "price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=12, scale=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "price",
        existing_type=sa.Numeric(precision=12, scale=3),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("fk_orders_delivery_city_id_delivery_cities"), "orders", type_="foreignkey"
    )
    op.drop_index(op.f("ix_orders_delivery_city_id"), table_name="orders")
    op.alter_column(
        "orders",
        "total",
        existing_type=sa.Numeric(precision=12, scale=3),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "delivery_fee",
        existing_type=sa.Numeric(precision=12, scale=3),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "subtotal",
        existing_type=sa.Numeric(precision=12, scale=3),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.drop_column("orders", "delivery_city_id")
    op.alter_column(
        "order_items",
        "line_total",
        existing_type=sa.Numeric(precision=12, scale=3),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "order_items",
        "unit_price",
        existing_type=sa.Numeric(precision=12, scale=3),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.drop_table("delivery_cities")
    # ### end Alembic commands ###
