"""size photos

Revision ID: 229565016a18
Revises: 6a3ba01d95a4
Create Date: 2026-09-28 12:22:45.409918

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "229565016a18"
down_revision: str | Sequence[str] | None = "6a3ba01d95a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_variants", sa.Column("image_path", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_variants", "image_path")
    # ### end Alembic commands ###
