"""Delegations (mu'tamadiyat) of each governorate, for the delivery address.

279 delegations per the 2024 census, from Wikipedia (fr: « Délégation (Tunisie) »), with English
and Arabic names from Wikidata. Keyed by the governorate's French name; each entry is
(French, English, Arabic).
"""

DELEGATIONS: dict[str, tuple[tuple[str, str, str], ...]] = {
    "Ariana": (
        ("Ariana Ville", "Ariana Ville", "أريانة المدينة"),
        ("Ettadhamen", "Ettadhamen", "التضامن"),
        ("Kalâat el-Andalous", "Kalâat el-Andalous", "قلعة الأندلس"),
        ("La Soukra", "La Soukra", "سكرة"),
        ("Mnihla", "Mnihla", "المنيهلة"),
        ("Raoued", "Raoued", "رواد"),
        ("Sidi Thabet", "Sidi Thabet", "سيدي ثابت"),
    ),
    "Béja": (
        ("Amdoun", "Amdoun", "عمدون"),
        ("Béja Nord", "Béja Nord", "باجة الشمالية"),
        ("Béja Sud", "Béja Sud", "باجة الجنوبية"),
        ("Goubellat", "Goubellat", "قبلاط"),
        ("Medjez el-Bab", "Medjez el-Bab", "مجاز الباب"),
        ("Nefza", "Nefza", "نفزة"),
        ("Téboursouk", "Téboursouk", "تبرسق"),
        ("Testour", "Testour", "تستور"),
        ("Thibar", "Thibar", "تيبار"),
    ),
    "Ben Arous": (
        ("Ben Arous", "Ben Arous", "بن عروس"),
        ("Bou Mhel el-Bassatine", "Bou Mhel el-Bassatine", "بومهل البساتين"),
        ("El Mourouj", "El Mourouj", "المروج"),
        ("Ezzahra", "Ezzahra", "الزهراء"),
        ("Fouchana", "Fouchana", "فوشانة"),
        ("Hammam Chott", "Hammam Chott", "حمام الشط"),
        ("Hammam Lif", "Hammam-Lif", "حمام الأنف"),
        ("Medina Jedida", "Medina Jedida", "المدينة الجديدة"),
        ("Mégrine", "Mégrine", "مقرين"),
        ("Mohamedia", "Mohamedia", "المحمدية"),
        ("Mornag", "Mornag", "مرناق"),
        ("Radès", "Radès", "رادس"),
    ),
    "Bizerte": (
        ("Bizerte Nord", "Bizerte Nord", "بنزرت الشمالية"),
        ("Bizerte Sud", "Bizerte Sud", "بنزرت الجنوبية"),
        ("El Alia", "El Alia", "العالية"),
        ("Ghar El Melh", "Ghar El Melh", "غار الملح"),
        ("Ghezala", "Ghezala", "غزالة"),
        ("Joumine", "Joumine", "جومين"),
        ("Mateur", "Mateur", "ماطر"),
        ("Menzel Bourguiba", "Menzel Bourguiba", "منزل بورقيبة"),
        ("Menzel Jemil", "Menzel Jemil", "منزل جميل"),
        ("Ras Jebel", "Ras Jebel", "رأس الجبل"),
        ("Sejnane", "Sejnane", "سجنان"),
        ("Tinja", "Tinja", "تينجة"),
        ("Utique", "Utique", "أوتيك"),
        ("Zarzouna", "Zarzouna", "جرزونة"),
    ),
    "Gabès": (
        ("El Hamma", "El Hamma", "الحامة"),
        ("El Hamma Ouest", "El Hamma Ouest", "الحامة الغربية"),
        ("Gabès Médina", "Gabès Médina", "قابس المدينة"),
        ("Gabès Ouest", "Gabès Ouest", "قابس الغربية"),
        ("Gabès Sud", "Gabès Sud", "قابس الجنوبية"),
        ("Ghannouch", "Ghannouch", "غنوش"),
        ("Mareth-Dkhila", "Mareth-Dkhila", "مارث"),
        ("Matmata", "Matmata", "مطماطة"),
        ("Menzel El Habib", "Menzel El Habib", "منزل الحبيب"),
        ("Métouia", "Métouia", "المطوية"),
        ("Nouvelle Matmata", "Nouvelle Matmata", "مطماطة الجديدة"),
        ("Oudhref", "Oudhref", "وذرف"),
        ("Toujane", "Toujane", "توجان"),
    ),
    "Gafsa": (
        ("Belkhir", "Belkhir", "بالخير"),
        ("El Guettar", "El Guettar", "القطار"),
        ("El Ksar", "El Ksar", "القصر"),
        ("Gafsa Nord", "Gafsa Nord", "قفصة الشمالية"),
        ("Gafsa Sud", "Gafsa Sud", "قفصة الجنوبية"),
        ("Mdhilla", "Mdhilla", "المظيلة"),
        ("Métlaoui", "Métlaoui", "المتلوي"),
        ("Moularès", "Moularès", "أم العرائس"),
        ("Redeyef", "Redeyef", "الرديف"),
        ("Sened", "Sened", "السند"),
        ("Sidi Aïch", "Sidi Aïch", "سيدي عيش"),
        ("Sidi Boubaker", "Sidi Boubaker", "سيدي بوبكر"),
        ("Zannouch", "Zannouch", "زنوش"),
    ),
    "Jendouba": (
        ("Aïn Draham", "Aïn Draham", "عين دراهم"),
        ("Balta-Bou Aouane", "Balta-Bou Aouane", "بلطة بوعوان"),
        ("Bou Salem", "Bou Salem", "بوسالم"),
        ("Fernana", "Fernana", "فرنانة"),
        ("Ghardimaou", "Ghardimaou", "غار الدماء"),
        ("Jendouba", "Jendouba", "جندوبة"),
        ("Jendouba Nord", "Jendouba Nord", "جندوبة الشمالية"),
        ("Oued Meliz", "Oued Meliz", "وادي مليز"),
        ("Tabarka", "Tabarka", "طبرقة"),
    ),
    "Kairouan": (
        ("Aïn Djeloula", "Aïn Djeloula", "عين جلولة"),
        ("Bou Hajla", "Bou Hajla", "بوحجلة"),
        ("Chebika", "Chebika", "الشبيكة"),
        ("Echrarda", "Echrarda", "الشراردة"),
        ("El Alâa", "El Alâa", "العلا"),
        ("Haffouz", "Haffouz", "حفوز"),
        ("Hajeb El Ayoun", "Hajeb El Ayoun", "حاجب العيون"),
        ("Kairouan Nord", "Kairouan Nord", "القيروان الشمالية"),
        ("Kairouan Sud", "Kairouan Sud", "القيروان الجنوبية"),
        ("Menzel Mehiri", "Menzel Mehiri", "منزل المهيري"),
        ("Nasrallah", "Nasrallah", "نصر الله"),
        ("Oueslatia", "Oueslatia", "الوسلاتية"),
        ("Sbikha", "Sbikha", "السبيخة"),
    ),
    "Kasserine": (
        ("El Ayoun", "El Ayoun", "العيون"),
        ("Ezzouhour", "Ezzouhour", "الزهور"),
        ("Fériana", "Fériana", "فريانة"),
        ("Foussana", "Foussana", "فوسانة"),
        ("Haïdra", "Haïdra", "حيدرة"),
        ("Hassi El Ferid", "Hassi El Ferid", "حاسي الفريد"),
        ("Jedelienne", "Jedelienne", "جدليان"),
        ("Kasserine Nord", "Kasserine Nord", "القصرين الشمالية"),
        ("Kasserine Sud", "Kasserine Sud", "القصرين الجنوبية"),
        ("Majel Bel Abbès", "Majel Bel Abbès", "ماجل بلعباس"),
        ("Sbeïtla", "Sbeïtla", "سبيطلة"),
        ("Sbiba", "Sbiba", "سبيبة"),
        ("Thala", "Thala", "تالة"),
    ),
    "Kébili": (
        ("Douz Nord", "Douz Nord", "دوز الشمالية"),
        ("Douz Sud", "Douz Sud", "دوز الجنوبية"),
        ("Faouar", "Faouar", "الفوار"),
        ("Kébili Nord", "Kébili Nord", "قبلي الشمالية"),
        ("Kébili Sud", "Kébili Sud", "قبلي الجنوبية"),
        ("Rjim Maatoug", "Rjim Maatoug", "رجيم معتوق"),
        ("Souk Lahad", "Souk Lahad", "سوق الأحد"),
    ),
    "La Manouba": (
        ("Borj El Amri", "Borj El Amri", "برج العامري"),
        ("Djedeida", "Djedeida", "الجديدة"),
        ("Douar Hicher", "Douar Hicher", "دوار هيشر"),
        ("El Batan", "El Batan", "البطان"),
        ("La Manouba", "La Manouba", "منوبة"),
        ("Mornaguia", "Mornaguia", "المرناقية"),
        ("Oued Ellil", "Oued Ellil", "وادي الليل"),
        ("Tebourba", "Tebourba", "طبربة"),
    ),
    "Le Kef": (
        ("Dahmani", "Dahmani", "الدهماني"),
        ("El Ksour", "El Ksour", "القصور"),
        ("Jérissa", "Jérissa", "الجريصة"),
        ("Kalâat Khasba", "Kalâat Khasba", "القلعة الخصبة"),
        ("Kalaat Senan", "Kalaat Senan", "قلعة سنان"),
        ("Kef Est", "Kef Est", "الكاف الشرقية"),
        ("Kef Ouest", "Kef Ouest", "الكاف الغربية"),
        ("Nebeur", "Nebeur", "نبر"),
        ("Sakiet Sidi Youssef", "Sakiet Sidi Youssef", "ساقية سيدي يوسف"),
        ("Sers", "Sers", "السرس"),
        ("Tajerouine", "Tajerouine", "تاجروين"),
        ("Touiref", "Touiref", "الطويرف"),
    ),
    "Mahdia": (
        ("Bou Merdes", "Bou Merdes", "بومرداس"),
        ("Chebba", "Chebba", "الشابة"),
        ("Chorbane", "Chorbane", "شربان"),
        ("El Bradâa", "El Bradâa", "البرادعة"),
        ("El Jem", "El Jem", "الجم"),
        ("Essouassi", "Essouassi", "السواسي"),
        ("Hebira", "Hebira", "هبيرة"),
        ("Ksour Essef", "Ksour Essef", "قصور الساف"),
        ("Mahdia", "Mahdia", "المهدية"),
        ("Melloulèche", "Melloulèche", "ملولش"),
        ("Ouled Chamekh", "Ouled Chamekh", "أولاد الشامخ"),
        ("Rejiche", "Rejiche", "رجيش"),
        ("Sidi Alouane", "Sidi Alouane", "سيدي علوان"),
    ),
    "Médenine": (
        ("Ben Gardane", "Ben Gardane", "بنقردان"),
        ("Beni Khedache", "Beni Khedache", "بني خداش"),
        ("Djerba - Ajim", "Djerba - Ajim", "جربة أجيم"),
        ("Djerba - Houmt Souk", "Djerba - Houmt Souk", "جربة حومة السوق"),
        ("Djerba - Midoun", "Djerba - Midoun", "جربة ميدون"),
        ("Médenine Nord", "Médenine Nord", "مدنين الشمالية"),
        ("Médenine Sud", "Médenine Sud", "مدنين الجنوبية"),
        ("Sidi Makhlouf", "Sidi Makhlouf", "سيدي مخلوف"),
        ("Zarzis", "Zarzis", "جرجيس"),
    ),
    "Monastir": (
        ("Bekalta", "Bekalta", "البقالطة"),
        ("Bembla", "Bembla", "بنبلة"),
        ("Beni Hassen", "Beni Hassen", "بني حسان"),
        ("Jemmal", "Jemmal", "جمال"),
        ("Ksar Hellal", "Ksar Hellal", "قصر هلال"),
        ("Ksibet el-Médiouni", "Ksibet el-Médiouni", "قصيبة المديوني"),
        ("Moknine", "Moknine", "المكنين"),
        ("Monastir", "Monastir", "المنستير"),
        ("Ouerdanine", "Ouerdanine", "الوردانين"),
        ("Sahline", "Sahline", "الساحلين"),
        ("Sayada-Lamta-Bou Hajar", "Sayada-Lamta-Bou Hajar", "صيادة لمطة بوحجر"),
        ("Téboulba", "Téboulba", "طبلبة"),
        ("Zéramdine", "Zéramdine", "زرمدين"),
    ),
    "Nabeul": (
        ("Béni Khalled", "Béni Khalled", "بني خلاد"),
        ("Béni Khiar", "Béni Khiar", "بني خيار"),
        ("Bou Argoub", "Bou Argoub", "بوعرقوب"),
        ("Dar Chaâbane El Fehri", "Dar Châabane El Fehri", "دار شعبان الفهري"),
        ("El Haouaria", "El Haouaria", "الهوارية"),
        ("El Mida", "El Mida", "الميدة"),
        ("Grombalia", "Grombalia", "قرمبالية"),
        ("Hammam Ghezèze", "Hammam Ghezèze", "حمام الأغزاز"),
        ("Hammamet", "Hammamet", "الحمامات"),
        ("Kélibia", "Kélibia", "قليبية"),
        ("Korba", "Korba", "قربة"),
        ("Menzel Bouzelfa", "Menzel Bouzelfa", "منزل بوزلفة"),
        ("Menzel Temime", "Menzel Temime", "منزل تميم"),
        ("Nabeul", "Nabeul", "نابل"),
        ("Soliman", "Soliman", "سليمان"),
        ("Takelsa", "Takelsa", "تاكلسة"),
    ),
    "Sfax": (
        ("Agareb", "Agareb", "عقارب"),
        ("Bir Ali Ben Khalifa", "Bir Ali Ben Khalifa", "بئر علي بن خليفة"),
        ("El Amra", "El Amra", "العامرة"),
        ("El Hencha", "El Hencha", "الحنشة"),
        ("Graïba", "Graïba", "الغريبة"),
        ("Jebiniana", "Jebiniana", "جبنيانة"),
        ("Kerkennah", "Kerkennah", "قرقنة"),
        ("Mahrès", "Mahrès", "المحرس"),
        ("Menzel Chaker", "Menzel Chaker", "منزل شاكر"),
        ("Sakiet Eddaïer", "Sakiet Eddaïer", "ساقية الدائر"),
        ("Sakiet Ezzit", "Sakiet Ezzit", "ساقية الزيت"),
        ("Sfax Ouest", "Sfax Ouest", "صفاقس الغربية"),
        ("Sfax Sud", "Sfax Sud", "صفاقس الجنوبية"),
        ("Sfax Ville", "Sfax Ville", "صفاقس المدينة"),
        ("Skhira", "Skhira", "الصخيرة"),
        ("Thyna", "Thyna", "طينة"),
    ),
    "Sidi Bouzid": (
        ("Bir El Hafey", "Bir El Hafey", "بئر الحفي"),
        ("Cebbala Ouled Asker", "Cebbala Ouled Asker", "سبالة أولاد عسكر"),
        ("Essaïda", "Essaïda", "السعيدة"),
        ("Hichria", "Hichria", "الهيشرية"),
        ("Jilma", "Jilma", "جلمة"),
        ("Meknassy", "Meknassy", "المكناسي"),
        ("Menzel Bouzaiane", "Menzel Bouzaiane", "منزل بوزيان"),
        ("Mezzouna", "Mezzouna", "المزونة"),
        ("Ouled Haffouz", "Ouled Haffouz", "أولاد حفوز"),
        ("Regueb", "Regueb", "الرقاب"),
        ("Sidi Ali Ben Aoun", "Sidi Ali Ben Aoun", "سيدي علي بن عون"),
        ("Sidi Bouzid Est", "Sidi Bouzid Est", "سيدي بوزيد الشرقية"),
        ("Sidi Bouzid Ouest", "Sidi Bouzid Ouest", "سيدي بوزيد الغربية"),
        ("Souk Jedid", "Souk Jedid", "السوق الجديد"),
    ),
    "Siliana": (
        ("Bargou", "Bargou", "برقو"),
        ("Bou Arada", "Bou Arada", "بوعرادة"),
        ("El Aroussa", "El Aroussa", "العروسة"),
        ("El Krib", "El Krib", "الكريب"),
        ("Gaâfour", "Gaâfour", "قعفور"),
        ("Kesra", "Kesra", "كسرى"),
        ("Makthar", "Makthar", "مكثر"),
        ("Rouhia", "Rouhia", "الروحية"),
        ("Sidi Bou Rouis", "Sidi Bou Rouis", "سيدي بورويس"),
        ("Siliana Nord", "Siliana Nord", "سليانة الشمالية"),
        ("Siliana Sud", "Siliana Sud", "سليانة الجنوبية"),
    ),
    "Sousse": (
        ("Akouda", "Akouda", "أكودة"),
        ("Bouficha", "Bouficha", "بوفيشة"),
        ("Enfida", "Enfida", "النفيضة"),
        ("Hammam Sousse", "Hammam Sousse", "حمام سوسة"),
        ("Hergla", "Hergla", "هرقلة"),
        ("Kalâa Kebira", "Kalâa Kebira", "القلعة الكبرى"),
        ("Kalâa Seghira", "Kalâa Seghira", "القلعة الصغرى"),
        ("Kondar", "Kondar", "كندار"),
        ("M'saken", "M'saken", "مساكن"),
        ("Sidi Bou Ali", "Sidi Bou Ali", "سيدي بوعلي"),
        ("Sidi El Hani", "Sidi El Hani", "سيدي الهاني"),
        ("Sousse Jawhara", "Sousse Jawhara", "سوسة جوهرة"),
        ("Sousse Médina", "Sousse Médina", "سوسة المدينة"),
        ("Sousse Riadh", "Sousse Riadh", "سوسة الرياض"),
        ("Sousse Sidi Abdelhamid", "Sousse Sidi Abdelhamid", "سوسة سيدي عبد الحميد"),
        ("Zaouiet Ksibet Thrayet", "Zaouiet Ksibet Thrayet", "زاوية قصيبة الثريات"),
    ),
    "Tataouine": (
        ("Beni Mhira", "Beni Mhira", "بني مهيرة"),
        ("Bir Lahmar", "Bir Lahmar", "بئر الأحمر"),
        ("Dehiba", "Dehiba", "الذهيبة"),
        ("Ghomrassen", "Ghomrassen", "غمراسن"),
        ("Remada", "Remada", "رمادة"),
        ("Smâr", "Smâr", "الصمار"),
        ("Tataouine Nord", "Tataouine Nord", "تطاوين الشمالية"),
        ("Tataouine Sud", "Tataouine Sud", "تطاوين الجنوبية"),
    ),
    "Tozeur": (
        ("Degache", "Degache", "دقاش"),
        ("El Hamma du Jérid", "El Hamma du Jérid", "حامة الجريد"),
        ("Hazoua", "Hazoua", "حزوة"),
        ("Nefta", "Nefta", "نفطة"),
        ("Tameghza", "Tameghza", "تمغزة"),
        ("Tozeur", "Tozeur", "توزر"),
    ),
    "Tunis": (
        ("Bab El Bhar", "Bab El Bhar", "باب البحر"),
        ("Bab Souika", "Bab Souika", "باب سويقة"),
        ("Carthage", "Carthage", "قرطاج"),
        ("Cité El Khadra", "Cité El Khadra", "حي الخضراء"),
        ("Djebel Jelloud", "Djebel Jelloud", "جبل الجلود"),
        ("El Kabaria", "El Kabaria", "الكبارية"),
        ("El Menzah", "El Menzah", "المنزه"),
        ("El Omrane", "El Omrane", "العمران"),
        ("El Omrane supérieur", "El Omrane supérieur", "العمران الأعلى"),
        ("El Ouardia", "El Ouardia", "الوردية"),
        ("Ettahrir", "Ettahrir", "التحرير"),
        ("Ezzouhour", "Ezzouhour", "الزهور"),
        ("Hraïria", "Hraïria", "الحرايرية"),
        ("La Goulette", "La Goulette", "حلق الوادي"),
        ("La Marsa", "La Marsa", "المرسى"),
        ("Le Bardo", "Le Bardo", "باردو"),
        ("Le Kram", "Le Kram", "الكرم"),
        ("Médina", "Medina", "المدينة"),
        ("Séjoumi", "Séjoumi", "السيجومي"),
        ("Sidi El Béchir", "Sidi El Béchir", "سيدي البشير"),
        ("Sidi Hassine", "Sidi Hassine", "سيدي حسين"),
    ),
    "Zaghouan": (
        ("Bir Mcherga", "Bir Mcherga", "بئر مشارقة"),
        ("El Fahs", "El Fahs", "الفحص"),
        ("Nadhour", "Nadhour", "الناظور"),
        ("Saouaf", "Saouaf", "صواف"),
        ("Zaghouan", "Zaghouan", "زغوان"),
        ("Zriba", "Zriba", "الزريبة"),
    ),
}
