/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_products__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Order */
        post: operations["create_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Order */
        get: operations["track_order_api_orders_track_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_admin_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_admin_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_admin_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_admin_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_admin_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_admin_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_api_admin_categories__category_id__patch"];
        trace?: never;
    };
    "/api/admin/categories/{category_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Category Image */
        post: operations["upload_category_image_api_admin_categories__category_id__image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_admin_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_admin_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_admin_products__product_id__get"];
        put?: never;
        post?: never;
        /** Delete Product */
        delete: operations["delete_product_api_admin_products__product_id__delete"];
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_api_admin_products__product_id__patch"];
        trace?: never;
    };
    "/api/admin/products/{product_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Product Image */
        post: operations["upload_product_image_api_admin_products__product_id__image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{product_id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Variant */
        post: operations["add_variant_api_admin_products__product_id__variants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/variants/{variant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Variant */
        delete: operations["delete_variant_api_admin_variants__variant_id__delete"];
        options?: never;
        head?: never;
        /** Update Variant */
        patch: operations["update_variant_api_admin_variants__variant_id__patch"];
        trace?: never;
    };
    "/api/admin/variants/{variant_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Variant Image */
        post: operations["upload_variant_image_api_admin_variants__variant_id__image_post"];
        /** Delete Variant Image */
        delete: operations["delete_variant_image_api_admin_variants__variant_id__image_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_admin_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_api_admin_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{order_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Order Status */
        post: operations["set_order_status_api_admin_orders__order_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notification Settings */
        get: operations["get_notification_settings_api_admin_notifications_get"];
        /** Update Notification Settings */
        put: operations["update_notification_settings_api_admin_notifications_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Test Email */
        post: operations["send_test_email_api_admin_notifications_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delivery-cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Active Cities */
        get: operations["list_active_cities_api_delivery_cities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/delivery-cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cities */
        get: operations["list_cities_api_admin_delivery_cities_get"];
        put?: never;
        /** Create City */
        post: operations["create_city_api_admin_delivery_cities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/delivery-cities/{city_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete City */
        delete: operations["delete_city_api_admin_delivery_cities__city_id__delete"];
        options?: never;
        head?: never;
        /** Update City */
        patch: operations["update_city_api_admin_delivery_cities__city_id__patch"];
        trace?: never;
    };
    "/api/admin/delivery-cities/{city_id}/delegations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Delegation */
        post: operations["create_delegation_api_admin_delivery_cities__city_id__delegations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/delegations/{delegation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Delegation */
        delete: operations["delete_delegation_api_admin_delegations__delegation_id__delete"];
        options?: never;
        head?: never;
        /** Update Delegation */
        patch: operations["update_delegation_api_admin_delegations__delegation_id__patch"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Config */
        get: operations["public_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminOut */
        AdminOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
        };
        /** AdminStatsOut */
        AdminStatsOut: {
            /** Orders By Status */
            orders_by_status: {
                [key: string]: number;
            };
            /** Revenue Delivered */
            revenue_delivered: string;
            /** Low Stock */
            low_stock: components["schemas"]["LowStockOut"][];
            /** Low Stock Threshold */
            low_stock_threshold: number;
        };
        /** Body_upload_category_image_api_admin_categories__category_id__image_post */
        Body_upload_category_image_api_admin_categories__category_id__image_post: {
            /** File */
            file: string;
        };
        /** Body_upload_product_image_api_admin_products__product_id__image_post */
        Body_upload_product_image_api_admin_products__product_id__image_post: {
            /** File */
            file: string;
        };
        /** Body_upload_variant_image_api_admin_variants__variant_id__image_post */
        Body_upload_variant_image_api_admin_variants__variant_id__image_post: {
            /** File */
            file: string;
        };
        /** CategoryAdminOut */
        CategoryAdminOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Name Ar */
            name_ar: string | null;
            /** Sort Order */
            sort_order: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Product Count
             * @default 0
             */
            product_count: number;
            /** Image Url */
            readonly image_url: string | null;
        };
        /** CategoryIn */
        CategoryIn: {
            /** Slug */
            slug: string;
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Name Ar */
            name_ar?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Name Ar */
            name_ar: string | null;
            /** Sort Order */
            sort_order: number;
            /** Image Url */
            readonly image_url: string | null;
        };
        /** CategoryPatch */
        CategoryPatch: {
            /** Slug */
            slug?: string | null;
            /** Name En */
            name_en?: string | null;
            /** Name Fr */
            name_fr?: string | null;
            /** Name Ar */
            name_ar?: string | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** DelegationAdminOut */
        DelegationAdminOut: {
            /** Id */
            id: number;
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Name Ar */
            name_ar: string | null;
            /** City Id */
            city_id: number;
            /** Sort Order */
            sort_order: number;
            /** Is Active */
            is_active: boolean;
        };
        /** DelegationIn */
        DelegationIn: {
            /** Name Fr */
            name_fr: string;
            /** Name En */
            name_en?: string | null;
            /** Name Ar */
            name_ar?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** DelegationOut */
        DelegationOut: {
            /** Id */
            id: number;
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Name Ar */
            name_ar: string | null;
        };
        /** DelegationPatch */
        DelegationPatch: {
            /** Name Fr */
            name_fr?: string | null;
            /** Name En */
            name_en?: string | null;
            /** Name Ar */
            name_ar?: string | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** DeliveryCityAdminOut */
        DeliveryCityAdminOut: {
            /** Id */
            id: number;
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Name Ar */
            name_ar: string | null;
            /** Fee */
            fee: string;
            /** Delegations */
            delegations: components["schemas"]["DelegationAdminOut"][];
            /** Sort Order */
            sort_order: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Order Count
             * @default 0
             */
            order_count: number;
        };
        /** DeliveryCityIn */
        DeliveryCityIn: {
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Name Ar */
            name_ar?: string | null;
            /** Fee */
            fee: number | string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * DeliveryCityOut
         * @description A governorate with the delegations customers can pick in it.
         */
        DeliveryCityOut: {
            /** Id */
            id: number;
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Name Ar */
            name_ar: string | null;
            /** Fee */
            fee: string;
            /** Delegations */
            delegations: components["schemas"]["DelegationOut"][];
        };
        /** DeliveryCityPatch */
        DeliveryCityPatch: {
            /** Name En */
            name_en?: string | null;
            /** Name Fr */
            name_fr?: string | null;
            /** Name Ar */
            name_ar?: string | null;
            /** Fee */
            fee?: number | string | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LowStockOut
         * @description A size running low (or out).
         */
        LowStockOut: {
            /** Variant Id */
            variant_id: number;
            /** Product Id */
            product_id: number;
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Weight Grams */
            weight_grams: number;
            /** Stock */
            stock: number;
            /** Is Available */
            is_available: boolean;
        };
        /**
         * MailServerOut
         * @description Where email is sent from (read-only; set by environment variables).
         */
        MailServerOut: {
            /** Enabled */
            enabled: boolean;
            /** Host */
            host: string;
            /** Port */
            port: number;
            /** Sender */
            sender: string;
        };
        /** NotificationSettingsIn */
        NotificationSettingsIn: {
            /** Admin Recipients */
            admin_recipients?: string[];
            /**
             * Admin Language
             * @default fr
             * @enum {string}
             */
            admin_language: "en" | "fr";
            /**
             * Notify Admin New Order
             * @default true
             */
            notify_admin_new_order: boolean;
            /**
             * Notify Admin Status Change
             * @default true
             */
            notify_admin_status_change: boolean;
            /**
             * Notify Admin Low Stock
             * @default true
             */
            notify_admin_low_stock: boolean;
            /**
             * Low Stock Threshold
             * @default 5
             */
            low_stock_threshold: number;
            /**
             * Notify Customer Confirmation
             * @default true
             */
            notify_customer_confirmation: boolean;
            /**
             * Notify Customer Validated
             * @default false
             */
            notify_customer_validated: boolean;
            /**
             * Notify Customer Shipped
             * @default false
             */
            notify_customer_shipped: boolean;
            /**
             * Notify Customer Delivered
             * @default true
             */
            notify_customer_delivered: boolean;
            /**
             * Notify Customer Cancelled
             * @default true
             */
            notify_customer_cancelled: boolean;
        };
        /** NotificationSettingsOut */
        NotificationSettingsOut: {
            /** Admin Recipients */
            admin_recipients?: string[];
            /**
             * Admin Language
             * @default fr
             * @enum {string}
             */
            admin_language: "en" | "fr";
            /**
             * Notify Admin New Order
             * @default true
             */
            notify_admin_new_order: boolean;
            /**
             * Notify Admin Status Change
             * @default true
             */
            notify_admin_status_change: boolean;
            /**
             * Notify Admin Low Stock
             * @default true
             */
            notify_admin_low_stock: boolean;
            /**
             * Low Stock Threshold
             * @default 5
             */
            low_stock_threshold: number;
            /**
             * Notify Customer Confirmation
             * @default true
             */
            notify_customer_confirmation: boolean;
            /**
             * Notify Customer Validated
             * @default false
             */
            notify_customer_validated: boolean;
            /**
             * Notify Customer Shipped
             * @default false
             */
            notify_customer_shipped: boolean;
            /**
             * Notify Customer Delivered
             * @default true
             */
            notify_customer_delivered: boolean;
            /**
             * Notify Customer Cancelled
             * @default true
             */
            notify_customer_cancelled: boolean;
            mail_server?: components["schemas"]["MailServerOut"] | null;
        };
        /** OrderAdminOut */
        OrderAdminOut: {
            /** Code */
            code: string;
            status: components["schemas"]["OrderStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** City */
            city: string;
            /** Delegation */
            delegation: string;
            /** Subtotal */
            subtotal: string;
            /** Delivery Fee */
            delivery_fee: string;
            /** Total */
            total: string;
            /** Items */
            items: components["schemas"]["OrderItemOut"][];
            /** Events */
            events: components["schemas"]["StatusEventOut"][];
            /** Id */
            id: number;
            /** Customer Name */
            customer_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string | null;
            /** Address */
            address: string;
            /** Notes */
            notes: string;
            /** Locale */
            locale: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Allowed Transitions
             * @default []
             */
            allowed_transitions: components["schemas"]["OrderStatus"][];
        };
        /** OrderConflictOut */
        OrderConflictOut: {
            /** Detail */
            detail: string;
            /** Problems */
            problems: components["schemas"]["StockProblem"][];
        };
        /** OrderCreatedOut */
        OrderCreatedOut: {
            /** Code */
            code: string;
            /** Total */
            total: string;
        };
        /** OrderIn */
        OrderIn: {
            /** Customer Name */
            customer_name: string;
            /** Phone */
            phone: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Address */
            address: string;
            /** Delivery City Id */
            delivery_city_id: number;
            /** Delegation Id */
            delegation_id: number;
            /**
             * Locale
             * @default fr
             * @enum {string}
             */
            locale: "en" | "fr" | "ar";
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Items */
            items: components["schemas"]["OrderLineIn"][];
        };
        /** OrderItemOut */
        OrderItemOut: {
            /** Product Id */
            product_id: number | null;
            /** Variant Id */
            variant_id: number | null;
            /** Product Name */
            product_name: string;
            /** Product Name Fr */
            product_name_fr: string;
            /** Product Name Ar */
            product_name_ar: string | null;
            /** Weight Grams */
            weight_grams: number | null;
            /** Unit Price */
            unit_price: string;
            /** Quantity */
            quantity: number;
            /** Line Total */
            line_total: string;
        };
        /** OrderLineIn */
        OrderLineIn: {
            /** Variant Id */
            variant_id: number;
            /** Quantity */
            quantity: number;
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "pending" | "validated" | "shipped" | "delivered" | "cancelled";
        /** OrderSummaryOut */
        OrderSummaryOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            status: components["schemas"]["OrderStatus"];
            /** Customer Name */
            customer_name: string;
            /** Phone */
            phone: string;
            /** City */
            city: string;
            /** Delegation */
            delegation: string;
            /** Total */
            total: string;
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrderTrackOut */
        OrderTrackOut: {
            /** Code */
            code: string;
            status: components["schemas"]["OrderStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** City */
            city: string;
            /** Delegation */
            delegation: string;
            /** Subtotal */
            subtotal: string;
            /** Delivery Fee */
            delivery_fee: string;
            /** Total */
            total: string;
            /** Items */
            items: components["schemas"]["OrderItemOut"][];
            /** Events */
            events: components["schemas"]["PublicStatusEventOut"][];
        };
        /** Page[OrderSummaryOut] */
        Page_OrderSummaryOut_: {
            /** Items */
            items: components["schemas"]["OrderSummaryOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[ProductAdminOut] */
        Page_ProductAdminOut_: {
            /** Items */
            items: components["schemas"]["ProductAdminOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[ProductOut] */
        Page_ProductOut_: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** ProductAdminOut */
        ProductAdminOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Category Id */
            category_id: number;
            /** Brand */
            brand: string | null;
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Name Ar */
            name_ar: string | null;
            /** Description En */
            description_en: string;
            /** Description Fr */
            description_fr: string;
            /** Description Ar */
            description_ar: string;
            /** Is Featured */
            is_featured: boolean;
            /** In Stock */
            in_stock: boolean;
            /** Min Price */
            min_price: string | null;
            /** Variants */
            variants: components["schemas"]["VariantAdminOut"][];
            /** Ingredients En */
            ingredients_en: string;
            /** Ingredients Fr */
            ingredients_fr: string;
            /** Ingredients Ar */
            ingredients_ar: string;
            /** Storage En */
            storage_en: string;
            /** Storage Fr */
            storage_fr: string;
            /** Storage Ar */
            storage_ar: string;
            /** Shelf Life Months */
            shelf_life_months: number | null;
            /** Is Available */
            is_available: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Image Url */
            readonly image_url: string | null;
        };
        /** ProductDetailOut */
        ProductDetailOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Category Id */
            category_id: number;
            /** Brand */
            brand: string | null;
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Name Ar */
            name_ar: string | null;
            /** Description En */
            description_en: string;
            /** Description Fr */
            description_fr: string;
            /** Description Ar */
            description_ar: string;
            /** Is Featured */
            is_featured: boolean;
            /** In Stock */
            in_stock: boolean;
            /** Min Price */
            min_price: string | null;
            /** Variants */
            variants: components["schemas"]["VariantDetailOut"][];
            category: components["schemas"]["CategoryOut"];
            /** Ingredients En */
            ingredients_en: string;
            /** Ingredients Fr */
            ingredients_fr: string;
            /** Ingredients Ar */
            ingredients_ar: string;
            /** Storage En */
            storage_en: string;
            /** Storage Fr */
            storage_fr: string;
            /** Storage Ar */
            storage_ar: string;
            /** Shelf Life Months */
            shelf_life_months: number | null;
            /** Image Url */
            readonly image_url: string | null;
        };
        /** ProductIn */
        ProductIn: {
            /** Brand */
            brand?: string | null;
            /**
             * Description En
             * @default
             */
            description_en: string;
            /**
             * Description Fr
             * @default
             */
            description_fr: string;
            /**
             * Ingredients En
             * @default
             */
            ingredients_en: string;
            /**
             * Ingredients Fr
             * @default
             */
            ingredients_fr: string;
            /**
             * Ingredients Ar
             * @default
             */
            ingredients_ar: string;
            /**
             * Storage En
             * @default
             */
            storage_en: string;
            /**
             * Storage Fr
             * @default
             */
            storage_fr: string;
            /**
             * Storage Ar
             * @default
             */
            storage_ar: string;
            /** Name Ar */
            name_ar?: string | null;
            /**
             * Description Ar
             * @default
             */
            description_ar: string;
            /** Shelf Life Months */
            shelf_life_months?: number | null;
            /**
             * Is Available
             * @default true
             */
            is_available: boolean;
            /**
             * Is Featured
             * @default false
             */
            is_featured: boolean;
            /** Category Id */
            category_id: number;
            /** Slug */
            slug: string;
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Variants */
            variants: components["schemas"]["VariantIn"][];
        };
        /** ProductOut */
        ProductOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Category Id */
            category_id: number;
            /** Brand */
            brand: string | null;
            /** Name En */
            name_en: string;
            /** Name Fr */
            name_fr: string;
            /** Name Ar */
            name_ar: string | null;
            /** Description En */
            description_en: string;
            /** Description Fr */
            description_fr: string;
            /** Description Ar */
            description_ar: string;
            /** Is Featured */
            is_featured: boolean;
            /** In Stock */
            in_stock: boolean;
            /** Min Price */
            min_price: string | null;
            /** Variants */
            variants: components["schemas"]["VariantOut"][];
            /** Image Url */
            readonly image_url: string | null;
        };
        /** ProductPatch */
        ProductPatch: {
            /** Category Id */
            category_id?: number | null;
            /** Slug */
            slug?: string | null;
            /** Name En */
            name_en?: string | null;
            /** Name Fr */
            name_fr?: string | null;
            /** Brand */
            brand?: string | null;
            /** Description En */
            description_en?: string | null;
            /** Description Fr */
            description_fr?: string | null;
            /** Ingredients En */
            ingredients_en?: string | null;
            /** Ingredients Fr */
            ingredients_fr?: string | null;
            /** Ingredients Ar */
            ingredients_ar?: string | null;
            /** Storage En */
            storage_en?: string | null;
            /** Storage Fr */
            storage_fr?: string | null;
            /** Storage Ar */
            storage_ar?: string | null;
            /** Name Ar */
            name_ar?: string | null;
            /** Description Ar */
            description_ar?: string | null;
            /** Shelf Life Months */
            shelf_life_months?: number | null;
            /** Is Available */
            is_available?: boolean | null;
            /** Is Featured */
            is_featured?: boolean | null;
        };
        /**
         * PublicStatusEventOut
         * @description Timeline entry shown to customers: no staff notes.
         */
        PublicStatusEventOut: {
            from_status: components["schemas"]["OrderStatus"] | null;
            to_status: components["schemas"]["OrderStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StatusChangeIn */
        StatusChangeIn: {
            to_status: components["schemas"]["OrderStatus"];
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** StatusEventOut */
        StatusEventOut: {
            from_status: components["schemas"]["OrderStatus"] | null;
            to_status: components["schemas"]["OrderStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Note */
            note: string;
        };
        /** StockProblem */
        StockProblem: {
            /** Variant Id */
            variant_id: number;
            /** Reason */
            reason: string;
            /**
             * Available
             * @default 0
             */
            available: number;
        };
        /** TestEmailIn */
        TestEmailIn: {
            /** To */
            to?: string[] | null;
        };
        /** TestEmailOut */
        TestEmailOut: {
            /** Sent To */
            sent_to: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariantAdminOut */
        VariantAdminOut: {
            /** Id */
            id: number;
            /** Weight Grams */
            weight_grams: number;
            /** Price */
            price: string;
            /** In Stock */
            in_stock: boolean;
            /** Stock */
            stock: number;
            /** Is Available */
            is_available: boolean;
            /** Sort Order */
            sort_order: number;
            /** Image Url */
            readonly image_url: string | null;
        };
        /** VariantDetailOut */
        VariantDetailOut: {
            /** Id */
            id: number;
            /** Weight Grams */
            weight_grams: number;
            /** Price */
            price: string;
            /** In Stock */
            in_stock: boolean;
            /** Stock */
            stock: number;
            /** Image Url */
            readonly image_url: string | null;
        };
        /** VariantIn */
        VariantIn: {
            /** Weight Grams */
            weight_grams: number;
            /** Price */
            price: number | string;
            /**
             * Stock
             * @default 0
             */
            stock: number;
            /**
             * Is Available
             * @default true
             */
            is_available: boolean;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** VariantOut */
        VariantOut: {
            /** Id */
            id: number;
            /** Weight Grams */
            weight_grams: number;
            /** Price */
            price: string;
            /** In Stock */
            in_stock: boolean;
            /** Image Url */
            readonly image_url: string | null;
        };
        /** VariantPatch */
        VariantPatch: {
            /** Weight Grams */
            weight_grams?: number | null;
            /** Price */
            price?: number | string | null;
            /** Stock */
            stock?: number | null;
            /** Expected Stock */
            expected_stock?: number | null;
            /** Is Available */
            is_available?: boolean | null;
            /** Sort Order */
            sort_order?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    list_products_api_products_get: {
        parameters: {
            query?: {
                category?: string | null;
                q?: string | null;
                featured?: boolean | null;
                sort?: "featured" | "newest" | "price_asc" | "price_desc" | "name";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProductOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_products__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderCreatedOut"];
                };
            };
            /** @description Stock changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderConflictOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_order_api_orders_track_get: {
        parameters: {
            query: {
                code: string;
                phone: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderTrackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_admin_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_admin_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_admin_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_admin_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryAdminOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_api_admin_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_admin_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_admin_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_category_image_api_admin_categories__category_id__image_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_category_image_api_admin_categories__category_id__image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_admin_products_get: {
        parameters: {
            query?: {
                category_id?: number | null;
                q?: string | null;
                available?: boolean | null;
                low_stock?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProductAdminOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_admin_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_admin_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_api_admin_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_admin_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_product_image_api_admin_products__product_id__image_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_product_image_api_admin_products__product_id__image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_variant_api_admin_products__product_id__variants_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_variant_api_admin_variants__variant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_variant_api_admin_variants__variant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_variant_image_api_admin_variants__variant_id__image_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_variant_image_api_admin_variants__variant_id__image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_variant_image_api_admin_variants__variant_id__image_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_admin_orders_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["OrderStatus"] | null;
                q?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OrderSummaryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_admin_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_order_status_api_admin_orders__order_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notification_settings_api_admin_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_notification_settings_api_admin_notifications_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_test_email_api_admin_notifications_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestEmailIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestEmailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_active_cities_api_delivery_cities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCityOut"][];
                };
            };
        };
    };
    list_cities_api_admin_delivery_cities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCityAdminOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_city_api_admin_delivery_cities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryCityIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCityAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_city_api_admin_delivery_cities__city_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_city_api_admin_delivery_cities__city_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryCityPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryCityAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_delegation_api_admin_delivery_cities__city_id__delegations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelegationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DelegationAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_delegation_api_admin_delegations__delegation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                delegation_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_delegation_api_admin_delegations__delegation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                delegation_id: number;
            };
            cookie?: {
                mj_admin?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelegationPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DelegationAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    public_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
